<?php
$session = Mage::getSingleton('checkout/session');
$orderIncrementId = $session->getLastRealOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
$isTestMode = Mage::getStoreConfig('payment/arca/testmode') == '1' ? 'test_':'';
$transactionId = Mage::getSingleton('checkout/session')->getArcaTransactionId();
  
$urlString = Mage::getUrl('arca/processing/result', array('_secure' => false, '_current' => true,'order_id'=>$order->getId()));
$url = Mage::getSingleton('core/url')->parseUrl($urlString);
$path = $url->getPath();
$gateway_url =Mage::getStoreConfig("payment/arca/{$isTestMode}gateway_url");
$data = array
(
'hostID'=>Mage::getStoreConfig("payment/arca/{$isTestMode}hostID")	,
'tid'=>Mage::getStoreConfig("payment/arca/{$isTestMode}tid")	,
'mid'=>Mage::getStoreConfig("payment/arca/{$isTestMode}mid")	,
'orderID'=>$transactionId	,
'currency'=>'051'	,
'amount'=>$this->normaizePrice($order->getGrandTotal())	,
'additionalURL'=>	$path


);
?>
<form method="post" action="<?php echo $gateway_url?>">

<?php foreach($data as $item=>$value):?>
	<input type="hidden" value="<?php echo $value?>"  name="<?php echo $item?>" />
<?php endforeach;?>
<button class="arca-payment-submit"><?php echo $this->__("Paye With arca")?></button>
</form>